apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1-webmain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webmain
  template:
    metadata:
      labels:
        app: webmain
    spec:
      containers:
        - name: pod-webmain
          image: seozzang3/home:v2.0
---
apiVersion: v1
kind: Service
metadata:
  name: svc1-webmain
spec:
  ports:
    - name: webmain-port
      port: 9001
      targetPort: 80
  selector:
    app: webmain
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy2-webcontact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcontact
  template:
    metadata:
      labels:
        app: webcontact
    spec:
      containers:
        - name: pod-webcontact
          image: seozzang3/contact:v2.0
---
apiVersion: v1
kind: Service
metadata:
  name: svc2-webcontact
spec:
  ports:
    - name: webcontact-port
      port: 9002
      targetPort: 80
  selector:
    app: webcontact
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy3-webevent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webevent
  template:
    metadata:
      labels:
        app: webevent
    spec:
      containers:
        - name: pod-webevent
          image: seozzang3/event:v2.0
---
apiVersion: v1
kind: Service
metadata:
  name: svc3-webevent
spec:
  ports:
    - name: webevent-port
      port: 9003
      targetPort: 80
  selector:
    app: webevent
  type: NodePort
 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-server
  template:
    metadata:
      labels:
        app: backend-server
    spec:
      containers:
        - name: pod-backend-server
          image: seozzang3/node:v1.1

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: backend-server
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000