apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1-webmain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webmain
  template:
    metadata:
      labels:
        app: webmain
    spec:
      containers:
        - name: pod-webmain
          image: seozzang3/home:v1.0
---
apiVersion: v1
kind: Service
metadata:
  name: svc1-webmain
spec:
  ports:
    - name: webmain-port
      port: 9001
      targetPort: 80
  selector:
    app: webmain
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy2-webabout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webabout
  template:
    metadata:
      labels:
        app: webabout
    spec:
      containers:
        - name: pod-webabout
          image: seozzang3/about:v1.0
---
apiVersion: v1
kind: Service
metadata:
  name: svc2-webabout
spec:
  ports:
    - name: webabout-port
      port: 9002
      targetPort: 80
  selector:
    app: webabout
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy3-webevent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webevent
  template:
    metadata:
      labels:
        app: webevent
    spec:
      containers:
        - name: pod-webevent
          image: seozzang3/event:v1.0
---
apiVersion: v1
kind: Service
metadata:
  name: svc3-webevent
spec:
  ports:
    - name: webevent-port
      port: 9003
      targetPort: 80
  selector:
    app: webevent
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy4-webschedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webschedule
  template:
    metadata:
      labels:
        app: webschedule
    spec:
      containers:
        - name: pod-webschedule
          image: seozzang3/schedule:v1.0
---
apiVersion: v1
kind: Service
metadata:
  name: svc4-webschedule
spec:
  ports:
    - name: webschedule-port
      port: 9004
      targetPort: 80
  selector:
    app: webschedule
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy5-webspeakers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webspeakers
  template:
    metadata:
      labels:
        app: webspeakers
    spec:
      containers:
        - name: pod-webspeakers
          image: seozzang3/speakers:v1.0
---
apiVersion: v1
kind: Service
metadata:
  name: svc5-webspeakers
spec:
  ports:
    - name: webspeakers-port
      port: 9005
      targetPort: 80
  selector:
    app: webspeakers
  type: NodePort
