apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1-webmain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webmain
  template:
    metadata:
      labels:
        app: webmain
    spec:
      containers:
        - name: pod-webmain
          image: registry.gitlab.com/ywon5355/test-project:v1.0
---
apiVersion: v1
kind: Service
metadata:
  name: svc1-webmain
spec:
  ports:
    - name: webmain-port
      port: 9001
      targetPort: 80
  selector:
    app: webmain
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy2-webevent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webevent
  template:
    metadata:
      labels:
        app: webevent
    spec:
      containers:
        - name: pod-webevent
          image: seozzang3/events:v2.0
---
apiVersion: v1
kind: Service
metadata:
  name: svc2-webevent
spec:
  ports:
    - name: webevent-port
      port: 9002
      targetPort: 80
  selector:
    app: webevent
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy3-webschedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webschedule
  template:
    metadata:
      labels:
        app: webschedule
    spec:
      containers:
        - name: pod-webschedule
          image: httpd
---
apiVersion: v1
kind: Service
metadata:
  name: svc3-webschedule
spec:
  ports:
    - name: webschedule-port
      port: 9003
      targetPort: 80
  selector:
    app: webschedule
  type: NodePort
